Repository eleven-labs/blog.eleven-labs.com, pull requests merged in 2018-04, with the labels that each got.

#469 fix typo on api platform article
  _posts/en/2017-08-24-api-platform-en.md
  _posts/fr/2017-07-25-api-platform.md
Labels: RFR, fix

#458 RabbitMQ des bases à la maîtrise (Partie 2)
  _posts/fr/2018-04-11-rabbitmq-partie-2-la-maitrise.md
  assets/2018-04-11-rabbitmq-partie-2-la-maitrise/cover.jpg
  assets/2018-04-11-rabbitmq-partie-2-la-maitrise/rabbitmq-permissions.png
  assets/2018-04-11-rabbitmq-partie-2-la-maitrise/rabbitmq-policies.png
  assets/2018-04-11-rabbitmq-partie-2-la-maitrise/rabbitmq-retry.jpg
  assets/2018-04-11-rabbitmq-partie-2-la-maitrise/rabbitmq-x-death-header.jpg
Labels: RFR, publication

#465 New post: livre blanc : l'architecture logicielle, tout ce que vous
  _posts/fr/2018-04-18-livre-blanc-architecture.md
  assets/2018-04-05-livre-blanc-architecture/button.jpg
  assets/2018-04-05-livre-blanc-architecture/cover.jpg
Labels: RFR, mergeable

#475 Add rmasclef author page.
  _authors/rmasclef.md
  img/authors/rmasclef.jpg
Labels: publication

#477 style(h2): fix h2 which was inline
  _sass/includes/_md-content.scss
Labels: RFR, fix
