Repository eleven-labs/blog.eleven-labs.com, pull requests merged in 2018-06, with the labels that each got.

#488 post(en, ext): should you go hybrid
  _authors/limor.wainstein.md
  _posts/en/2018-06-06-should-you-go-hybrid.md
  assets/2018-06-06-should-you-go-hybrid/cover.jpg
  img/authors/limor.wainstein.jpg
Labels: mergeable

#489 Feat/add article Symfony 4
  _posts/fr/2018-06-11-php-socket.md
  _posts/fr/2018-06-11-symfony-4.md
  assets/2018-06-11-symfony-4/cover.jpg
Labels: RFR, publication

#490 Delete article not ready
  _posts/fr/2018-06-11-php-socket.md
Labels: fix, publication
