Repository eleven-labs/blog.eleven-labs.com, pull requests merged in 2018-03, with the labels that each got.

#417 Add link for article exception
  _posts/en/2016-11-17-php_handle-exception-gracefully.md
  _posts/en/2018-02-11-throwable-error-exception.md
  _posts/fr/2016-11-16-php_bien-gerer-ses-exceptions.md
  _posts/fr/2018-02-11-throwable-error-exception.md
Labels: RFR

#420 RabbitMQ des bases à la maîtrise (Partie 1)
  _posts/fr/2018-03-11-rabbitmq-partie-1-les-bases.md
  assets/2018-03-11-rabbitmq-partie-1-les-bases/cover.jpg
  assets/2018-03-11-rabbitmq-partie-1-les-bases/rabbitmq-broker.jpg
  assets/2018-03-11-rabbitmq-partie-1-les-bases/rabbitmq-exchange-default.jpg
  assets/2018-03-11-rabbitmq-partie-1-les-bases/rabbitmq-exchange-direct.jpg
  assets/2018-03-11-rabbitmq-partie-1-les-bases/rabbitmq-exchange-fanaout.jpg
  assets/2018-03-11-rabbitmq-partie-1-les-bases/rabbitmq-exchange-headers.jpg
  assets/2018-03-11-rabbitmq-partie-1-les-bases/rabbitmq-exchange-topic.jpg
Labels: RFR, publication

#421 [Fix] RabbitMQ des bases à la maîtrise (Partie 1)
  _posts/fr/2018-03-11-rabbitmq-partie-1-les-bases.md
  assets/2018-03-11-rabbitmq-partie-1-les-bases/rabbitmq-exchange-fanout.jpg
Labels: RFR, fix, publication

#422 feat(font-awesome): update font-awesome to version 5
  _includes/author_link.html
  _includes/head.html
  _includes/icons.html
  _includes/scripts.html
  _includes/share.html
  _layouts/post.html
  index.html
  js/lib/fontawesome/svg-with-js/js/fa-brands.min.js
  js/lib/fontawesome/svg-with-js/js/fa-regular.min.js
  js/lib/fontawesome/svg-with-js/js/fa-solid.min.js
  js/lib/fontawesome/svg-with-js/js/fontawesome.min.js
Labels: RFR, feat

#401 perf(pagespeed): add pagespeed optimized files
  _includes/icons.html
  img/bg-header.jpg
  js/lib/js-cookie/js.cookie.min.js
  js/lib/moment/locale/fr.min.js
  js/lib/moment/moment.min.js
Labels: RFR, feat

#424 chore(ci): add slack message after master deploy
  .travis.yml
Labels: RFR, feat

#423 fix some markdown style
  _posts/fr/2018-03-11-rabbitmq-partie-1-les-bases.md
Labels: RFR, fix, publication

#428 fix(bin,slack): proper escaping and add attachment
  bin/notify-slack.sh
Labels: fix

#427 perf(css): move main css in an inline style tag
  _includes/head.html
  _includes/main.scss
  _includes/scripts.html
Labels: RFR, feat

#430 Add author kcordier
  _authors/kcordier.md
  img/authors/kcordier.jpg
Labels: publication

#439 Fix Rabbitmq title
  _posts/fr/2018-02-11-throwable-error-exception.md
  _posts/fr/2018-03-11-rabbitmq-partie-1-les-bases.md
Labels: RFR, fix, publication

#431 Feat/add article retour experience bem
  _posts/fr/2018-03-15-retour-d-experience-sur-bem.md
  assets/2018-03-15-retour-d-experience-sur-bem/bem_image.png
  assets/2018-03-15-retour-d-experience-sur-bem/cover.jpg
Labels: publication

#440 feat(tracking): improve event category granularity
  _includes/amp-icons.html
  _includes/icons.html
  _includes/share.html
  js/cookie-consent.js
Labels: WIP, feat

#418 feat - Add article for Cucumber / Calabash
  _posts/fr/2018-03-21-calabash-cucumber.md
  assets/2018-03-01-calabash-cucumber/SimoLoginError.png
  assets/2018-03-01-calabash-cucumber/SimuLogin.png
  assets/2018-03-01-calabash-cucumber/SimuRegister.png
  assets/2018-03-01-calabash-cucumber/SimuRegisterError.png
  assets/2018-03-01-calabash-cucumber/SmuHome2.png
  assets/2018-03-01-calabash-cucumber/calabash-ios-stack.png
  assets/2018-03-01-calabash-cucumber/cover.jpg
  assets/2018-03-01-calabash-cucumber/cucumber-feature@2x.png
  assets/2018-03-01-calabash-cucumber/dashboard.png
  assets/2018-03-01-calabash-cucumber/device_state.png
  assets/2018-03-01-calabash-cucumber/image-01.png
  assets/2018-03-01-calabash-cucumber/image-02.png
  assets/2018-03-01-calabash-cucumber/pool_create.png
  assets/2018-03-01-calabash-cucumber/pool_error.png
  assets/2018-03-01-calabash-cucumber/pool_success.png
  assets/2018-03-01-calabash-cucumber/run_exec_time.png
  assets/2018-03-01-calabash-cucumber/screen_home_feature.png
  assets/2018-03-01-calabash-cucumber/simuHome.png
  assets/2018-03-01-calabash-cucumber/upload_calabash.png
  assets/2018-03-01-calabash-cucumber/upload_ipa.png
  assets/2018-03-01-calabash-cucumber/upload_ipa_version.png
Labels: RFR, publication

#448 Fix error with image gherkin
  _posts/fr/2018-03-21-calabash-cucumber.md
  assets/2018-03-01-calabash-cucumber/gherkincheat.png
Labels: fix, publication

#449 Fix error typo
  _posts/fr/2018-03-21-calabash-cucumber.md
Labels: fix, publication

#450 bimm nouvelle page de bg
  _authors/babas.md
  img/authors/babas.jpg
Labels: publication

#457 Fix typos in GraphQL blog post
  _posts/fr/2018-03-28-graphql-kesako.md
Labels: RFR
