Repository eleven-labs/blog.eleven-labs.com, pull requests merged in 2019-02, with the labels that each got.

#556 [POST] what-is-an-architect
  _authors/pouzor.md
  _posts/fr/2019-02-06-what-is-an-architect.md
  assets/2019-02-06-what-is-an-architect/cover.jpg
  assets/2019-02-06-what-is-an-architect/hdd.png
  assets/2019-02-06-what-is-an-architect/triumvira.png
Labels: RFR, publication

#563 Add section about PR on fork
  README.md
Labels: mergeable

#567 fixed typos
  _posts/fr/2019-02-15-commencer-avec-apollojs.md
Labels: RFR
