Repository eleven-labs/blog.eleven-labs.com, pull requests merged in 2019-10, with the labels that each got.

#698 Article 2/3 Une application React plus réactive - Le skeleton screen
  _posts/fr/2019-05-09-react-i18next.md
  _posts/fr/2019-07-26-optimistic-ui.md
  _posts/fr/2019-08-07-domotize-your-workspace.md
  _posts/fr/2019-10-16-skeleton-screen.md
  assets/2019-10-16-skeleton-screen/item_skeleton.gif
  assets/2019-10-16-skeleton-screen/list_item.png
  assets/2019-10-16-skeleton-screen/list_skeleton.gif
  assets/2019-10-16-skeleton-screen/list_skeleton_fail.gif
  assets/2019-10-16-skeleton-screen/loader.gif
  assets/2019-10-16-skeleton-screen/min_height.gif
  assets/2019-10-16-skeleton-screen/no_loading.gif
  assets/2019-10-16-skeleton-screen/skeleton.jpg
  assets/2019-10-16-skeleton-screen/skeleton_item.gif
  assets/2019-10-16-skeleton-screen/skeleton_linkedin.png
  assets/2019-10-16-skeleton-screen/skeleton_youtube.png
Labels: RFR, publication

#701 Add Manu to authors
  _authors/manu.md
  img/authors/manu.jpg
Labels: publication

#703 Ajout d'un lien vers l'article 1 de "UNE APPLICATION REACT PLUS RÉACT…
  _posts/fr/2019-10-16-skeleton-screen.md
Labels: fix
