Repository eleven-labs/blog.eleven-labs.com, pull requests merged in 2019-04, with the labels that each got.

#621 Add myself (mehdi) to author
  _authors/mehdidr.md
  img/authors/mehdidr.png
Labels: publication

#639 fix(git): remove case sensitive file
  fonts/Korb.woff
Labels: fix

#638 chore(ci): cache bundler & rendering directory
  .travis.yml
Labels: feat

#641 Add article les nouveautés d'es6
  _posts/fr/2019-04-17-les-nouveautes-es6-part-i.md
Labels: publication

#640 change variable content
  _includes/links.html
Labels: RFR
