Repository eleven-labs/blog.eleven-labs.com, pull requests merged in 2020-12, with the labels that each got.

#783 Translate monitor docker containers
  _posts/en/2020-12-09-monitor-your-docker-containers.md
Labels: publication

#785 Trad article traefik + add author's page
  _authors/dfert.md
  _posts/en/2020-12-15-using-traefik-as-a-reverse-proxy.md
  img/authors/dfert.jpg
Labels: publication

#788 chore(bump): bump amp jekyll gem
  Gemfile.lock
Labels: status/reviewable, type/chore

#791 chore(jekyll,git,travis): .jekyll-cache
  .gitignore
  .travis.yml
  _config.yml
Labels: mergeable, type/chore

#789 chore(bump): ruby version
  .ruby-version
Labels: status/mergeable, type/chore
