Repository eleven-labs/blog.eleven-labs.com, pull requests merged in 2020-09, with the labels that each got.

#768 chore(bundler): bump rouge 3.22.0
  Gemfile
  Gemfile.lock
Labels: status/mergeable, type/chore

#767 [2020-09-08] Gérer son organisation github avec terraform
  _posts/fr/2020-09-08-gerer-son-organisation-github-avec-terraform.md
  assets/2020-09-08-gerer-son-organisation-github-avec-terraform/github_model.png
Labels: status/wip, type/feat

#766 Add english article web video streaming
  _posts/en/2017-07-19-video-live-dash-hls.md
Labels: RFR, publication

#770 feat(author): update veberarnaud author page
  _authors/VEBERArnaud.md
Labels: status/reviewable, type/feat

#772 Add english article HTTPS part 1
  _posts/en/2020-09-16-https-part-1.md
Labels: RFR, publication

#774 add HTTPS Part 2 en post
  _posts/en/2020-09-23-https-part-2.md
Labels: RFR, publication

#775 post: monitorer son debit internet
  _posts/fr/2020-09-23-monitorer-son-debit-internet.md
  assets/2020-09-23-monitorer-son-debit-internet/dashboard.png
  assets/2020-09-23-monitorer-son-debit-internet/grafana_connect.gif
  assets/2020-09-23-monitorer-son-debit-internet/grafana_dashboard.gif
  assets/2020-09-23-monitorer-son-debit-internet/grafana_datasource.gif
  assets/2020-09-23-monitorer-son-debit-internet/schema.png
Labels: publication, status/wip

#778 Nouvel article : Les meilleurs outils pour dev js en 2020
  _posts/fr/2020-09-30-meilleurs-outils-js-2020.md
  assets/2020-09-30-meilleurs-outils-js-2020/bundlephobia.png
  assets/2020-09-30-meilleurs-outils-js-2020/docker.png
  assets/2020-09-30-meilleurs-outils-js-2020/header.jpg
  assets/2020-09-30-meilleurs-outils-js-2020/lighthouse.jpg
  assets/2020-09-30-meilleurs-outils-js-2020/lint-prettier.jpg
  assets/2020-09-30-meilleurs-outils-js-2020/storybook.png
  assets/2020-09-30-meilleurs-outils-js-2020/webpack-visualizer.png
Labels: RFR, publication
