Repository eleven-labs/blog.eleven-labs.com, pull requests merged in 2020-05, with the labels that each got.

#750 Add new article - PHP & Serverless - part 1
  _posts/en/2020-05-06-php-serverless-part-1.md
  _posts/fr/2018-11-07-debutons-avec-le-serverless.md
  _posts/fr/2020-05-06-php-serverless-part-1.md
  assets/2020-05-06-php-serverless-part-1/aws-limitations.png
Labels: RFR, publication

#751 Add PHP / Serverless part 2 article
  _posts/en/2020-05-13-php-serverless-part-2.md
  _posts/fr/2020-05-13-php-serverless-part-2.md
  assets/2020-05-07-php-serverless-part-2/example.png
Labels: RFR, publication

#753 Nouvel article "Vous utilisez mal les states React"
  _authors/kcordier.md
  _posts/fr/2020-05-20-vous-utilisez-mal-les-states.md
  assets/2020-05-20-vous-utilisez-mal-les-states/bien-pas-bien.gif
Labels: RFR

#754 Fix double brace in jsx script
  _posts/fr/2020-05-20-vous-utilisez-mal-les-states.md
Labels: RFR, fix
