Repository eleven-labs/blog.eleven-labs.com, pull requests merged in 2021-03, with the labels that each got.

#810 Create 2021-03-04-bien-preparer-arrivee-de-equipe-de-developpement-pr…
  _posts/fr/2021-03-04-bien-preparer-arrivee-de-equipe-de-developpement-prestataire-sur-son-produit.md
Labels: publication

#811 Add article 'Les femmes dans l'informatique'
  _authors/marianne.md
  _posts/fr/2021-03-08-les-femmes-dans-linformatique.md
  assets/2021-03-08-les-femmes-dans-linformatique/first.jpg
  assets/2021-03-08-les-femmes-dans-linformatique/second.png
  assets/2021-03-08-les-femmes-dans-linformatique/third.png
Labels: RFR, publication

#812 Translate Women in IT
  _posts/en/2021-03-08-women-in-it.md
Labels: RFR, publication

#711 Fix external link
  _posts/fr/2018-10-03-introduction-gitlab-ci.md
Labels: RFR, fix
