Repository eleven-labs/blog.eleven-labs.com, pull requests merged in 2021-11, with the labels that each got.

#860 Update cookie-consent.js for adding google Analytics without cookie tracing
  _config.yml
  js/cookie-consent.js
Labels: mergeable

#863 fix(deploy): algolia indexing
  .github/workflows/deploy.yml
  Rakefile
Labels: status/reviewable, type/fix

#864 fix(gh_actions): pass algolia api key to the agolia push task
  .github/workflows/deploy.yml
Labels: status/mergeable, type/fix
