Repository eleven-labs/blog.eleven-labs.com, pull requests merged in 2021-08, with the labels that each got.

#838 Add author Sbessoudo
  _authors/sbessoudo.md
Labels: publication

#839 add article focus group
  _posts/fr/2021-08-17-focusgroup.md
Labels: publication

#844 Fix search bar + header text overflow
  _includes/footer.html
  _includes/header-variables.scss.liquid
  _sass/objects/_search-bar.scss
  _sass/settings/_variables.scss
Labels: fix, RFR, status/reviewable, type/fix

#845 Fix language switch in the footer
  _includes/footer.html
Labels: fix, RFR, status/reviewable
