Repository eleven-labs/blog.eleven-labs.com, pull requests merged in 2023-12, with the labels that each got.

#1042 feat: add article integration crm
  _articles/fr/2023-12-05-integration-crm.md
  _assets/articles/2023-12-05-integration-crm/integration-crm-schema-e-commerce-to-hubspot.png
  _assets/articles/2023-12-05-integration-crm/integration-crm-schema-global.png
  _assets/articles/2023-12-05-integration-crm/integration-crm-schema-hubspot-to-e-commerce.png
  _authors/fbelet.md
Labels: publication, status/reviewable

#1047 fix: nantes offices address
  src/config/website/contact.ts
Labels: fix, mergeable, status/reviewable

#1049 feat: add contact form link in footer
  src/config/website/contact.ts
  src/containers/LayoutTemplateContainer/useFooterContainer.tsx
  src/templates/LayoutTemplate/Footer/Footer.tsx
  src/templates/LayoutTemplate/LayoutTemplate.stories.tsx
  src/translations/en.translations.json
  src/translations/fr.translations.json
Labels: feat, status/reviewable

#1046 feat: remove cookie consent bar to replace by axept.io
  package.json
  src/components/CookieConsent/CookieConsent.scss
  src/components/CookieConsent/CookieConsent.stories.tsx
  src/components/CookieConsent/CookieConsent.tsx
  src/components/CookieConsent/index.ts
  src/config/website/common.ts
  src/containers/CookieConsentContainer/CookieConsentContainer.tsx
  src/containers/CookieConsentContainer/index.ts
  src/containers/CookieConsentContainer/useCookieConsentContainer.ts
  src/containers/LayoutTemplateContainer/useLayoutTemplateContainer.tsx
  src/entry-server.tsx
  src/templates/HtmlTemplate/HtmlTemplate.tsx
  src/templates/LayoutTemplate/LayoutTemplate.tsx
  src/translations/en.translations.json
  src/translations/fr.translations.json
  yarn.lock
Labels: feat, mergeable, status/reviewable

#1050 feat: SEO: update footer text content
  src/templates/LayoutTemplate/Footer/Footer.tsx
  src/translations/en.translations.json
  src/translations/fr.translations.json
Labels: feat, status/reviewable
