Repository eleven-labs/blog.eleven-labs.com, pull requests merged in 2023-10, with the labels that each got.

#984 fix: sort search by date
  src/helpers/indexationAlgoliaHelper.ts
Labels: status/mergeable, status/reviewable

#991 fix: correct assets path for img
  README.md
Labels: fix, status/reviewable

#994 feat: add integration mermaid diagram
  package.json
  src/containers/PostPageContainer/usePostPageContainer.tsx
  src/helpers/markdownToHtmlHelper.tsx
  yarn.lock
Labels: status/mergeable, status/reviewable

#997 Fix: Workflow PR Closed
  .github/workflows/pr-closed.yml
Labels: status/mergeable, status/reviewable

#989 Article EDD
  _assets/posts/2023-10-23-edd/event-driven-architecture-rabbitmq.png
  _posts/fr/2023-10-23-event-driven-architecture.md
Labels: publication, status/reviewable

#1003 fix: typo article 'les-commandes-git'
  _articles/fr/2023-10-26-how-to-git-gud.md
Labels: status/mergeable, status/reviewable

#999 feat: add design system article
  _articles/fr/2023-06-28-un-pont-entre-les-mondes-comment-les-design-tokens-facilitent-la-cooperation-entre-developpeurs-et-designers.md
  _articles/fr/2023-10-30-pourquoi-creer-design-system.md
  _assets/articles/2023-06-28-un-pont-entre-les-mondes-comment-les-design-tokens-facilitent-la-cooperation-entre-developpeurs-et-designers/specify.jpg
  _assets/articles/2023-06-28-un-pont-entre-les-mondes-comment-les-design-tokens-facilitent-la-cooperation-entre-developpeurs-et-designers/style-dictionary.png
  _assets/articles/2023-06-28-un-pont-entre-les-mondes-comment-les-design-tokens-facilitent-la-cooperation-entre-developpeurs-et-designers/supernova.webp
  _assets/articles/2023-06-28-un-pont-entre-les-mondes-comment-les-design-tokens-facilitent-la-cooperation-entre-developpeurs-et-designers/token-studio.jpg
  _assets/articles/2023-10-30-pourquoi-creer-design-system/design-system-decathlon.png
  _assets/articles/2023-10-30-pourquoi-creer-design-system/design-system-etat-francais.png
  _assets/articles/2023-10-30-pourquoi-creer-design-system/design-system-welcome-to-the-jungle.png
Labels: status/mergeable, status/reviewable

#1008 fix: typo articles les commandes git
  _articles/fr/2023-10-26-how-to-git-gud.md
Labels: status/mergeable, status/reviewable

#1011 migrate graphql avec symfony (codelabs)
  _assets/tutorials/2018-03-28-graphql-avec-symfony/cover.png
  _assets/tutorials/2018-03-28-graphql-avec-symfony/symfony.png
  _tutorials/fr/2018-03-28-graphql-avec-symfony/index.md
  _tutorials/fr/2018-03-28-graphql-avec-symfony/steps/configuration-de-la-bdd.md
  _tutorials/fr/2018-03-28-graphql-avec-symfony/steps/creation-des-types-graphql.md
  _tutorials/fr/2018-03-28-graphql-avec-symfony/steps/installation-du-serveur-graphql.md
  _tutorials/fr/2018-03-28-graphql-avec-symfony/steps/introduction.md
  _tutorials/fr/2018-03-28-graphql-avec-symfony/steps/resolver-des-mutations.md
  _tutorials/fr/2018-03-28-graphql-avec-symfony/steps/resolver-des-queries.md
Labels: status/mergeable, status/reviewable
