Repository eleven-labs/blog.eleven-labs.com, pull requests merged in 2023-11, with the labels that each got.

#1013 Migrate gitlab-ci avec une application js (codelabs)
  _assets/tutorials/2018-09-19-gitlab-ci-js/result-init-gitlab-ci.png
  _assets/tutorials/2018-09-19-gitlab-ci-js/screenshot-app-vue-js-init.png
  _assets/tutorials/2018-09-19-gitlab-ci-js/screenshot-cis-demo-production.png
  _assets/tutorials/2018-09-19-gitlab-ci-js/screenshot-create-project-gcp.png
  _assets/tutorials/2018-09-19-gitlab-ci-js/screenshot-create-project-gitlab.png
  _assets/tutorials/2018-09-19-gitlab-ci-js/screenshot-create-service-key.png
  _assets/tutorials/2018-09-19-gitlab-ci-js/screenshot-deploy-demo.png
  _assets/tutorials/2018-09-19-gitlab-ci-js/screenshot-deploy-production.png
  _assets/tutorials/2018-09-19-gitlab-ci-js/screenshot-gitlab-ci-cd-settings-variables.png
  _assets/tutorials/2018-09-19-gitlab-ci-js/screenshot-home-page-gcp-console.png
  _assets/tutorials/2018-09-19-gitlab-ci-js/screenshot-pipeline-build.png
  _assets/tutorials/2018-09-19-gitlab-ci-js/screenshot-pipeline-lint-and-test.png
  _assets/tutorials/2018-09-19-gitlab-ci-js/screenshot-protected-branch.png
  _assets/tutorials/2018-09-19-gitlab-ci-js/screenshot-protected-tag.png
  _assets/tutorials/2018-09-19-gitlab-ci-js/screenshot-version-app-demo-vs-prod.png
  _assets/tutorials/2018-09-19-gitlab-ci-js/workflow-gitlab-ci-app-js.svg
  _tutorials/fr/2018-09-19-gitlab-ci-js/index.md
  _tutorials/fr/2018-09-19-gitlab-ci-js/steps/definition-besoins-et-preparation-de-application.md
  _tutorials/fr/2018-09-19-gitlab-ci-js/steps/deploiement-application-google-cloud-platform.md
  _tutorials/fr/2018-09-19-gitlab-ci-js/steps/initialisation-ci-cd-et-preparation-application.md
  _tutorials/fr/2018-09-19-gitlab-ci-js/steps/introduction.md
  _tutorials/fr/2018-09-19-gitlab-ci-js/steps/mise-en-place-phases-code-style-et-tests.md
  _tutorials/fr/2018-09-19-gitlab-ci-js/steps/test-et-conclusion.md
Labels: status/mergeable, status/reviewable

#1015 Migrate Gestion d'environnement avec Google Cloud Storage et GitlabCI…
  _tutorials/fr/2019-07-29-react-env-variable-gcp-gitlabci/index.md
  _tutorials/fr/2019-07-29-react-env-variable-gcp-gitlabci/steps/creation-application-react.md
  _tutorials/fr/2019-07-29-react-env-variable-gcp-gitlabci/steps/deploiement-application-react-via-gitlab.md
  _tutorials/fr/2019-07-29-react-env-variable-gcp-gitlabci/steps/deploiement-du-projet-sur-app-engine.md
  _tutorials/fr/2019-07-29-react-env-variable-gcp-gitlabci/steps/introduction.md
  _tutorials/fr/2019-07-29-react-env-variable-gcp-gitlabci/steps/script-recuperation-fichiers-configuration.md
Labels: status/mergeable, status/reviewable

#1018 fix: style of tutorial stepper
  src/components/TutorialSteps/TutorialSteps.scss
Labels: status/mergeable, status/reviewable

#1017 Migrate Créez un chat avec Mercure et Symfony (codelabs)
  _tutorials/fr/2020-09-30-creez-un-chat-avec-symfony-et-mercure/index.md
  _tutorials/fr/2020-09-30-creez-un-chat-avec-symfony-et-mercure/steps/conclusion.md
  _tutorials/fr/2020-09-30-creez-un-chat-avec-symfony-et-mercure/steps/configuration-de-mercure.md
  _tutorials/fr/2020-09-30-creez-un-chat-avec-symfony-et-mercure/steps/discovery-abonnemen-et-publication-avec-mercure.md
  _tutorials/fr/2020-09-30-creez-un-chat-avec-symfony-et-mercure/steps/envoi-de-message.md
  _tutorials/fr/2020-09-30-creez-un-chat-avec-symfony-et-mercure/steps/gestion-securite-avec-mercure.md
  _tutorials/fr/2020-09-30-creez-un-chat-avec-symfony-et-mercure/steps/initialisation-du-projet.md
  _tutorials/fr/2020-09-30-creez-un-chat-avec-symfony-et-mercure/steps/introduction.md
  _tutorials/fr/2020-09-30-creez-un-chat-avec-symfony-et-mercure/steps/vues-et-logique-de-base.md
Labels: status/mergeable, status/reviewable

#1020 feat: update search result
  src/components/ArticleMetadata/ArticleMetadata.stories.tsx
  src/components/ArticleMetadata/ArticleMetadata.tsx
  src/components/ArticleMetadata/index.ts
  src/components/AutocompleteField/AutocompleteField.stories.tsx
  src/components/AutocompleteField/AutocompleteResult/AutocompleteResult.tsx
  src/components/PostPreview/PostPreview.stories.tsx
  src/components/PostPreview/PostPreview.tsx
  src/components/index.ts
  src/containers/HeaderContainer/useHeaderContainer.tsx
  src/helpers/indexationAlgoliaHelper.ts
  src/templates/LayoutTemplate/LayoutTemplate.stories.tsx
Labels: status/mergeable, status/reviewable

#1019 feat: add tutorial filter to list page
  src/config/schemaValidation/PostDataSchemaValidation.ts
  src/constants.ts
  src/helpers/contentHelper.ts
  src/helpers/loaderDataHelper.ts
  src/helpers/prerenderHelper/getSitemapEntries.test.ts
  src/helpers/prerenderHelper/getSitemapEntries.ts
  src/translations/en.translations.json
  src/translations/fr.translations.json
  src/types/PageData.ts
Labels: status/mergeable, status/reviewable

#1004 Feature/highlighted post preview
  src/components/PostPreview/PostPreview.scss
  src/components/PostPreview/PostPreview.stories.tsx
  src/components/PostPreview/PostPreview.tsx
  src/components/PostPreview/PostPreviewCard.tsx
  src/components/PostPreview/PostPreviewContent.tsx
  src/pages/PostListPage/PostListPage.stories.tsx
  src/pages/PostListPage/PostListPage.tsx
Labels: status/mergeable, status/reviewable

#1022 fix: highlighted post preview
  src/components/PostPreview/PostPreview.scss
  src/components/PostPreview/PostPreview.tsx
  src/components/PostPreview/PostPreviewCard.tsx
  src/components/PostPreview/PostPreviewContent.tsx
Labels: status/mergeable, status/reviewable

#1005 Article - Atomic Design
  _articles/fr/2023-11-03-atomic-design.md
  _assets/articles/2023-11-03-atomic-design/atomic-design-abstract-concrete.png
  _assets/articles/2023-11-03-atomic-design/atomic-design-final.png
  _assets/articles/2023-11-03-atomic-design/atomic-design-hierarchie.png
  _assets/articles/2023-11-03-atomic-design/atomic-design-system-product.png
  _assets/authors/iregaibi.png
  _authors/iregaibi.md
Labels: publication, status/reviewable

#1024 feat: Update author page for charles-eric
  _assets/authors/charles-eric.jpg
  _authors/charles-eric.md
Labels: feat, mergeable

#1026 fix: avoid react warnings
  src/components/ArticleMetadata/ArticleMetadata.tsx
  src/containers/HeaderContainer/useHeaderContainer.tsx
  src/containers/LinkContainer/LinkContainer.tsx
Labels: fix, mergeable

#1028 fix: expose port for hot reload via docker-compose
  docker-compose.yml
Labels: fix, mergeable

#1030 fix: typo in 404 page
  src/translations/fr.translations.json
Labels: fix, mergeable

#1029 fix: Correct syntax
  _articles/fr/2023-11-03-atomic-design.md
Labels: fix, status/reviewable

#1032 fix: feedbacks css tutorial stepper
  src/components/ArticleMetadata/ArticleMetadata.tsx
  src/components/PostPreview/PostPreviewContent.tsx
  src/components/TutoTag/TutoTag.scss
  src/components/TutorialSteps/TutorialSteps.scss
  src/components/TutorialSteps/TutorialSteps.tsx
Labels: status/mergeable, status/reviewable

#1031 fix: typo author fpasquet
  _authors/fpasquet.md
Labels: status/mergeable, status/reviewable

#1027 feat: add article micro frontend
  README.md
  _articles/fr/2023-11-06-micro-frontend.md
  _assets/articles/2023-11-06-micro-frontend/microfrontend-concept.png
  _assets/articles/2023-11-06-micro-frontend/microfrontend-progressive-migration.png
Labels: publication, status/reviewable

#1037 fix: react keys to avoid warnings and authors being mixed up
  src/components/ArticleMetadata/ArticleMetadata.tsx
  src/components/AutocompleteField/AutocompleteField.stories.tsx
  src/components/AutocompleteField/AutocompleteResult/AutocompleteResult.tsx
  src/components/PostPreview/PostPreview.stories.tsx
  src/components/PostPreview/PostPreview.tsx
  src/components/PostPreviewList/PostPreviewList.stories.tsx
  src/components/PostPreviewList/PostPreviewList.tsx
  src/components/TutorialSteps/TutorialSteps.tsx
  src/containers/HeaderContainer/useHeaderContainer.tsx
  src/pages/PostPage/RelatedPostList/RelatedPostList.tsx
Labels: fix, mergeable, status/reviewable

#1035 fix: microfrontend article typos
  _articles/fr/2023-11-06-micro-frontend.md
Labels: fix, mergeable, status/reviewable

#988 feat: Article REX plateforme data
  _articles/fr/2023-11-14-rex-plateforme-data.md
  _assets/articles/2023-11-14-rex-plateforme-data/architecture.png
Labels: publication, status/reviewable

#1041 fix: apply feedback for rex data platforme
  _articles/fr/2023-11-14-rex-plateforme-data.md
Labels: fix, publication

#1039 Article - Construire un Design System robuste avec react: les fondations essentielles
  _articles/fr/2023-11-28-construire-un-design-system-robuste-avec-react-les-fondations-essentielles.md
  _assets/articles/2023-11-28-construire-un-design-system-robuste-avec-react-les-fondations-essentielles/colors-design-token.png
  _assets/articles/2023-11-28-construire-un-design-system-robuste-avec-react-les-fondations-essentielles/postPreviewList-default.png
  _assets/articles/2023-11-28-construire-un-design-system-robuste-avec-react-les-fondations-essentielles/postPreviewList-loading.png
  _assets/articles/2023-11-28-construire-un-design-system-robuste-avec-react-les-fondations-essentielles/postPreviewList-pagination.png
Labels: publication, status/reviewable

#1043 feat: add post preview clickable
  src/components/PostPreview/PostPreview.scss
  src/components/PostPreview/PostPreviewContent.tsx
Labels: status/mergeable, status/reviewable
