Repository eleven-labs/blog.eleven-labs.com, pull requests merged in 2023-02, with the labels that each got.

#906 👷 Add lighthouse audit to github action
  .github/workflows/deploy.yml
  .github/workflows/lighthouse-config.js
  .github/workflows/lighthouseCommentMaker.js
  .github/workflows/lighthousesrc.json
  .github/workflows/pr-closed.yml
Labels: mergeable

#908 fix: ci audit lighthouse
  .github/workflows/deploy.yml
  .github/workflows/pr-closed.yml
Labels: mergeable

#909 💚 separate audit lighthouse into another workflow
  .github/workflows/audit-lighthouse.yml
  .github/workflows/deploy.yml
  .github/workflows/pr-closed.yml
Labels: status/mergeable

#902 Add new articles to migrate from a monolith to microservices
  _posts/en/2023-02-09-monolith-to-microservices.md
  _posts/fr/2023-02-09-monolith-to-microservices.md
Labels: publication, status/reviewable
