Repository eleven-labs/blog.eleven-labs.com, pull requests merged in 2023-04, with the labels that each got.

#924 feat: add deploy storybook on github pages
  .github/workflows/deploy-storybook.yml
  package.json
  yarn.lock
Labels: mergeable, status/reviewable

#923 feat: add unit tests
  .github/workflows/deploy.yml
  _authors/TEMPLATE-AUTOR
  _drafts/TEMPLATE-ARTICLE
  _posts/fr/2023-02-22-symfony-et-mongodb-retour-aux-sources.md
  bin/prerender.ts
  bin/validateAndFormatMarkdown/getValidCategories.ts
  bin/validateAndFormatMarkdown/index.ts
  bin/validateAndFormatMarkdown/markdownCleaning.ts
  bin/validateAndFormatMarkdown/validationSchema.ts
  bin/validateMarkdown.ts
  globalMocks.ts
  jest.config.ts
  package.json
  public/web-app-manifest.json
  src/app-paths.ts
  src/config/router/routes.tsx
  src/constants.ts
  src/constants/algolia.ts
  src/constants/categories.ts
  src/constants/index.ts
  src/constants/paths.ts
  src/containers/LayoutTemplateContainer/useLayoutTemplateContainer.tsx
  src/entry-server.tsx
  src/helpers/apiHelper.ts
  src/helpers/assetHelper.test.ts
  src/helpers/assetHelper.ts
  src/helpers/base64Helper.ts
  src/helpers/getEnvHelper.ts
  src/helpers/langHelper.ts
  src/helpers/objectHelper.test.ts
  src/helpers/objectHelper.ts
  src/helpers/prerenderHelper.ts
  src/helpers/ssrHelper.test.ts
  src/helpers/ssrHelper.ts
  src/helpers/stringHelper.test.ts
  src/helpers/validateMarkdownHelper.test.ts
  src/helpers/validateMarkdownHelper.ts
  src/hooks/useAlgoliaSearchIndex.ts
  src/server.ts
  src/templates/HtmlTemplate/HtmlTemplate.tsx
  yarn.lock
Labels: mergeable, status/reviewable

#925 Create 2023-04-20-comment-choisir-parmi-scrum-kanban-safe.md
  _assets/posts/2023-04-20-comment-choisir-parmi-scrum-kanban-safe/agile.png
  _assets/posts/2023-04-20-comment-choisir-parmi-scrum-kanban-safe/agile_train.jpg
  _assets/posts/2023-04-20-comment-choisir-parmi-scrum-kanban-safe/kanban1.jpg
  _assets/posts/2023-04-20-comment-choisir-parmi-scrum-kanban-safe/kanban_jira.png
  _assets/posts/2023-04-20-comment-choisir-parmi-scrum-kanban-safe/methodo_eleven.jpg
  _posts/fr/2023-04-20-comment-choisir-parmi-scrum-kanban-safe.md
Labels: mergeable, publication, status/reviewable

#927 Add gcunsolo author
  _assets/authors/gcunsolo.jpg
  _authors/gcunsolo.md
Labels: publication

#928 feat: update empty avatar img
  public/imgs/astronaut.png
  src/containers/AuthorPageContainer/useAuthorPageContainer.tsx
  src/containers/PostPageContainer/usePostPageContainer.tsx
  src/helpers/contentHelper.ts
  src/pages/AuthorPage/AuthorPage.scss
  src/pages/AuthorPage/AuthorPage.stories.tsx
  src/pages/AuthorPage/AuthorPage.tsx
  src/pages/PostPage/PostFooter/PostFooter.scss
  src/pages/PostPage/PostFooter/PostFooter.tsx
  src/pages/PostPage/PostPage.stories.tsx
Labels: status/mergeable, status/reviewable

#931 fix: allow any extension for the avatar image
  src/helpers/contentHelper.ts
Labels: status/mergeable, status/reviewable
