Repository eleven-labs/blog.eleven-labs.com, pull requests merged in 2023-05, with the labels that each got.

#930 Init article Archimate
  _assets/posts/2023-05-03-archi-modelisation/archi_screenshot_1.png
  _assets/posts/2023-05-03-archi-modelisation/archi_screenshot_2.png
  _assets/posts/2023-05-03-archi-modelisation/archi_screenshot_3.png
  _assets/posts/2023-05-03-archi-modelisation/archi_screenshot_4.png
  _assets/posts/2023-05-03-archi-modelisation/archi_screenshot_5.png
  _assets/posts/2023-05-03-archi-modelisation/archi_screenshot_6.png
  _assets/posts/2023-05-03-archi-modelisation/core_framework_archimate.jpeg
  _authors/pouzor.md
  _posts/fr/2023-05-03-archi-modelisation.md
Labels: feat, publication, status/reviewable

#937 Fix - Responsive video
  _posts/fr/2023-O5-10-instruction-debugger-et-points-arret.md
Labels: fix, publication

#939 feat: migrate jest to vitest
  .gitignore
  globalMocks.ts
  package.json
  src/helpers/ssrHelper.test.ts
  src/helpers/validateMarkdownHelper.test.ts
  src/setup-test.ts
  tsconfig.json
  vitest.config.ts
  yarn.lock
Labels: mergeable, status/reviewable
