Repository eleven-labs/blog.eleven-labs.com, pull requests merged in 2023-07, with the labels that each got.

#959 fix: json+ld content on all pages
  src/containers/AuthorPageContainer/useAuthorPageContainer.tsx
  src/containers/LayoutTemplateContainer/useLayoutTemplateContainer.tsx
  src/containers/NotFoundPageContainer/useNotFoundPageContainer.tsx
  src/containers/PostListPageContainer/usePostListPageContainer.tsx
  src/containers/PostPageContainer/usePostPageContainer.tsx
  src/containers/SearchPageContainer/useSearchPageContainer.tsx
  src/hooks/useSeo.ts
  src/hooks/useSeoPost.ts
  src/hooks/useTitle.ts
  src/pages/NotFoundPage/NotFoundPage.tsx
  src/templates/HtmlTemplate/HtmlTemplate.tsx
  src/translations/en.translations.json
  src/translations/fr.translations.json
Labels: mergeable, status/reviewable

#961 fix seo: updated hn, added SearchAction json ld and corrected category links
  src/components/AutocompleteField/AutocompleteResult/AutocompleteResult.tsx
  src/components/CookieConsent/CookieConsent.tsx
  src/components/NewsletterBlock/NewsletterBlock.tsx
  src/components/NotFoundBlock/NotFoundBlock.tsx
  src/config/website/common.ts
  src/containers/LayoutTemplateContainer/useLayoutTemplateContainer.tsx
  src/containers/PostListPageContainer/usePostListPageContainer.tsx
  src/pages/PostListPage/SubHeader/SubHeader.tsx
  src/pages/PostPage/PostHeader/PostHeader.tsx
  src/pages/PostPage/RelatedPostList/RelatedPostList.tsx
  src/pages/SearchPage/SearchPage.tsx
  src/templates/LayoutTemplate/Footer/Footer.tsx
Labels: status/mergeable, status/reviewable

#963 feat: add sitemap and fix url for author and post page
  _authors/limor.wainstein.md
  _posts/en/2016-11-17-php_handle-exception-gracefully.md
  _posts/en/2018-06-06-should-you-go-hybrid.md
  _posts/en/2019-05-09-manage-translations-with-localise.biz.md
  _posts/fr/2016-11-16-php_bien-gerer-ses-exceptions.md
  _posts/fr/2019-04-03-introduction-aux-hooks.md
  _posts/fr/2019-05-02-gestion-des-traductions-avec-localise.biz.md
  _posts/fr/2019-06-12-code-splitting-react.md
  _posts/fr/2019-08-14-REX-d-etudiant-a-developpeur-web.md
  _posts/fr/2019-09-25-rxSwift.md
  _posts/fr/2019-11-20-reprenez-le-controle-de-vos-file-system-avec-flysystem.md
  _posts/fr/2021-04-21-UX-Writing-Introduction-et-bonnes-pratiques.md
  _posts/fr/2021-11-03-Storybook-intro.md
  bin/build.ts
  bin/prerender.ts
  package.json
  public/robots.txt
  src/config/router/routes.tsx
  src/containers/AuthorPageContainer/useAuthorPageContainer.tsx
  src/containers/PostListPageContainer/usePostListPageContainer.tsx
  src/containers/SearchPageContainer/useSearchPageContainer.tsx
  src/helpers/markdownHelper.ts
  src/helpers/prerenderHelper.ts
  src/helpers/prerenderHelper/generateFeedFile.ts
  src/helpers/prerenderHelper/generateHtmlFiles.ts
  src/helpers/prerenderHelper/generateSitemap.ts
  src/helpers/prerenderHelper/getSitemapEntries.test.ts
  src/helpers/prerenderHelper/getSitemapEntries.ts
  src/helpers/prerenderHelper/index.ts
  yarn.lock
Labels: status/mergeable, status/reviewable

#964 fix: remove dev version react and upgrade libs
  package.json
  src/containers/CookieConsentContainer/useCookieConsentContainer.ts
  vite.config.ts
  yarn.lock
Labels: status/mergeable, status/reviewable

#965 :feat: :sparkles: Create ShareLinks component
  package.json
  src/components/ShareLinks/ShareLinks.scss
  src/components/ShareLinks/ShareLinks.stories.tsx
  src/components/ShareLinks/ShareLinks.tsx
  src/components/ShareLinks/index.tsx
  src/components/index.ts
  src/constants.ts
  src/hooks/useCopyToClipboard.ts
  src/pages/PostPage/PostPage.tsx
  src/translations/en.translations.json
  src/translations/fr.translations.json
  yarn.lock
Labels: status/reviewable
