Repository eleven-labs/blog.eleven-labs.com, pull requests merged in 2024-07, with the labels that each got.

#1131 feat: démarrer avec apache spark
  _articles/fr/2024-07-08-demarrer-apache-spark.md
Labels: publication, status/reviewable

#1136 fix: add cover for spark article
  _articles/fr/2024-07-08-demarrer-apache-spark.md
  _assets/articles/2024-07-08-demarrer-apache-spark/cover.jpg
Labels: mergeable

#1132 feat: Tester le code PySpark avec pytest
  _articles/fr/2024-07-23-tester-spark-avec-pytest.md
  _assets/articles/2024-07-23-tester-spark-avec-pytest/cover.jpg
Labels: mergeable, publication

#1141 feat(update-address): Update of address in Nantes
  src/config/website/contact.ts
Labels: status/mergeable, type/feat, status/reviewable
