Repository eleven-labs/blog.eleven-labs.com, pull requests merged in 2024-04, with the labels that each got.

#1087 fix: indexation cover
  src/containers/LayoutTemplateContainer/useHeaderContainer.tsx
  src/containers/SearchPageContainer/useSearchPageContentContainer.tsx
  src/helpers/indexationAlgoliaHelper.ts
  src/types/AlgoliaData.ts
Labels: status/mergeable, status/reviewable

#1088 fix: search page and update translations
  .github/workflows/checks-and-tests.yml
  .github/workflows/continuous-integration-and-deployment.yml
  bin/build.ts
  bin/downloadTranslations.ts
  bin/indexationAlgolia.ts
  bin/prerender.ts
  src/containers/CategoryPageContainer/useCategoryPageContainer.tsx
  src/containers/HomePageContainer/useHomePageContainer.tsx
  src/containers/PostCardListContainer/PostCardListContainer.tsx
  src/containers/PostCardListContainer/usePostCardListContainer.ts
  src/containers/SearchPageContainer/useSearchPageContentContainer.tsx
  src/helpers/downloadTranslationsHelper.ts
  src/translations/en.translations.json
  src/translations/fr.translations.json
Labels: status/mergeable, status/reviewable

#1089 fix feedback ui (line-clamp, pagination ...)
  package-lock.json
  package.json
  src/containers/SearchPageContainer/useSearchPageContentContainer.tsx
  src/translations/en.translations.json
  src/translations/fr.translations.json
Labels: status/mergeable, status/reviewable

#1090 fix: i18n initialization with island architecture
  src/entry-client.tsx
  src/templates/HtmlTemplate/HtmlTemplate.tsx
Labels: status/mergeable, status/reviewable

#1096 fix: remove angular in php description
  src/translations/en.translations.json
  src/translations/fr.translations.json
Labels: fix

#1093 fix: upgrade design system and fix breadcrumb
  package-lock.json
  package.json
  src/hooks/useBreadcrumb.ts
  src/hooks/usePostPage.tsx
Labels: status/mergeable, status/reviewable

#1111 fix: all blog urls must end /
  _articles/fr/2019-09-04-nouveautes-es-6-part-ii.md
  _articles/fr/2024-01-10-typage-generique-en-php.md
Labels: status/mergeable, status/reviewable

#1114 fix: table markdown
  package-lock.json
  package.json
  src/helpers/markdownToHtmlHelper.tsx
Labels: status/mergeable, status/reviewable

#1106 fix(webperf): add async on script mermaid
  src/containers/PostPageContainer/PostPageContainer.tsx
  src/entry-client.tsx
  src/helpers/markdownToHtmlHelper.tsx
  src/hooks/usePostPage.tsx
Labels: status/mergeable, status/reviewable

#1091 refactor: generate image with sharp
  README.md
  _articles/fr/2024-02-19-quelques-conseils-pour-optimiser-votre-environnement-de-travail-sous-linux.md
  _tutorials/fr/2024-03-27-chromatic/index.md
  src/config/i18n/i18n.config.ts
  src/config/router/routes.tsx
  src/config/schemaValidation/AuthorDataValidationSchema.ts
  src/config/schemaValidation/PostDataSchemaValidation.ts
  src/config/schemaValidation/TutorialStepDataValidationSchema.ts
  src/constants.ts
  src/containers/ArticlePageContainer/useArticlePageContainer.tsx
  src/containers/CategoryPageContainer/useCategoryPageContainer.tsx
  src/containers/HomePageContainer/useHomePageContainer.tsx
  src/containers/PostCardListContainer/usePostCardListContainer.ts
  src/containers/PostPageContainer/PostPageContainer.tsx
  src/containers/SearchPageContainer/useSearchPageContentContainer.tsx
  src/containers/TutorialPageContainer/useTutorialPageContainer.tsx
  src/entry-server.tsx
  src/helpers/assetHelper.ts
  src/helpers/contentHelper.ts
  src/helpers/downloadTranslationsHelper.ts
  src/helpers/generateImageFormats.ts
  src/helpers/loaderDataHelper.ts
  src/helpers/markdownContentManagerHelper.ts
  src/helpers/prerenderHelper/generateFeedFile.ts
  src/helpers/prerenderHelper/getSitemapEntries.test.ts
  src/helpers/prerenderHelper/getUrls.test.ts
  src/helpers/prerenderHelper/getUrls.ts
  src/hooks/usePostPage.tsx
  src/hooks/usePostsForCardList.ts
  src/middlewares/imageMiddleware.ts
  src/translations/en.translations.json
  src/translations/fr.translations.json
  src/types/CategoryType.ts
  src/types/ContentTypeData.ts
  src/types/DeviceType.ts
  src/types/ImageExtensionType.ts
  src/types/ImageFormatType.ts
  src/types/ImagePositionType.ts
  src/types/LanguageType.ts
  src/types/PageData.ts
  src/types/TransformedContentTypeData.ts
  src/types/index.ts
Labels: status/mergeable, status/reviewable

#1036 feat: RSS auto discovery
  src/containers/LayoutTemplateContainer/useLayoutTemplateContainer.tsx
Labels: feat, status/reviewable

#1110 fix: regex to detect external urls
  src/helpers/markdownToHtmlHelper.test.ts
  src/helpers/markdownToHtmlHelper.tsx
Labels: status/mergeable, status/reviewable

#1115 fix: url relative and absolute
  src/config/website/common.ts
  src/config/website/socialNetworks.ts
  src/containers/AuthorPageContainer/useAuthorPageContainer.tsx
  src/containers/CategoryPageContainer/useCategoryPageContainer.tsx
  src/containers/HomePageContainer/useHomePageContainer.tsx
  src/containers/LayoutTemplateContainer/useLayoutTemplateContainer.tsx
  src/containers/SearchPageContainer/useSearchPageContentContainer.tsx
  src/helpers/assetHelper.test.ts
  src/helpers/assetHelper.ts
  src/helpers/prerenderHelper/generateFeedFile.ts
  src/helpers/prerenderHelper/generateSitemap.ts
  src/hooks/useSeoPost.ts
  src/templates/HtmlTemplate/HtmlTemplate.tsx
Labels: status/mergeable, status/reviewable

#1119 fix: broken link on tutorial previous button
  src/containers/TutorialPageContainer/useTutorialPageContainer.tsx
Labels: status/mergeable, status/reviewable
